# Generated by Django 5.0.3 on 2024-05-05 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_commentaire_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='note',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
